/**
 * dsh-provider-usage —— 包组合根入口（#768 D13）。
 *
 * 薄转发：全部符号经 ./apply/index.ts（装配层组合根）透出，本文件不定义行为。
 * 为什么是显式具名转发而不是 export *：export-surface-snapshot 的提取器只读具名导出与声明块（不跟随星导出），星转发会让主入口导出面读出为空而判红。
 * 新增公共符号时两处同步加名（漂移即门禁红）。
 */
export { HotReloadableAdapter, ROUTES, apply, inject, name, sseData } from "./apply/index.ts";
export type {
  AdapterErrorCode,
  AdapterErrorInfo,
  AdapterInfo,
  AdapterRegistry,
  AdapterSource,
  AdapterUtils,
  CapsuleInput,
  DayRecord,
  DueExecutorDeps,
  DueReport,
  FetchContext,
  FloatBreakpoint,
  HistoryEntry,
  LastRunRecord,
  NormalizedConfig,
  PanelCacheEntry,
  PanelInput,
  ProviderConfigInput,
  RectLike,
  ReplaceFileResult,
  ReportConfig,
  ReportConfigServiceOptions,
  ReportLlmService,
  ReportMeta,
  ReportPeriod,
  ReportPeriodConfig,
  ReportPrompts,
  ReportResult,
  ReportStatsSnapshot,
  ReportTask,
  ReportTaskInput,
  ReportTaskResult,
  ReportTaskStatus,
  ReportTokenUsage,
  ResolvedProviderConfig,
  SamplePoint,
  TrendAggRow,
  TrendAttribution,
  TrendCallRecord,
  TrendCell,
  TrendCorrectRecord,
  TrendCounterRecord,
  TrendCounterRow,
  TrendDetailRow,
  TrendDirRow,
  TrendEmit,
  TrendGranularity,
  TrendHourRow,
  TrendMetric,
  TrendStackPart,
  TrendStackPoint,
  TrendTokens,
  TrendTrackerOptions,
  TrendWindowSummary,
  UiPlacementConfig,
  UsageStatsAdapter,
  UserAdapterRecord,
  ViewportPoint,
} from "./apply/index.ts";
