#!/usr/bin/env node
// @ts-nocheck
'use strict'

/**
 * aggregate — 聚合包（dsh-plugins-all）cordis.patch.yml 生成/校验器。
 *
 * 语义（对齐 web-ui aggregate 实测做法 + 本仓 ui-<name> patch id 决策）：
 *   - 聚合 cordis.patch.yml = 各独立包 insert 行**原样拼接**（id + name，**不带
 *     config**——schema 默认值兜底：lan-proxy host/port、mcp-manager
 *     announceToAgent、各插件 enabled 均有默认）；
 *   - 聚合行 id 与独立行 id 相同（ui-<目录名>）：同一插件以独立+聚合两种方式
 *     同时安装时，loader 层按 id 出现 duplicate -> TypeError（fail-loud 启动
 *     失败，明确可发现）；因此 **README 声明禁双装**（任选一种安装方式）。
 *     保持 id 相同而非另加前缀——避免「不同 id 双 entry 各自 apply 的静默双激活」。
 *   - AUTO-GENERATED 头，禁止手改；`--check` 模式漂移即失败（CI 门禁）。
 *
 * 用法：
 *   node scripts/aggregate.ts           # 重新生成聚合 patch
 *   node scripts/aggregate.ts --check   # 校验漂移（CI 用）
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')
const AGGREGATE_NAME = 'dsh-plugins-all'
const PATCH_PATH = join(ROOT, 'packages', AGGREGATE_NAME, 'cordis.patch.yml')
// 已退役插件：不再进入聚合 patch（dsh-gzip 压缩能力已合并进 dsh-lan-proxy，
// 见其 README 退役节；子包本身仍随仓发布至删除周期）。
const RETIRED = new Set(['dsh-gzip'])

/** 独立插件子包目录（排除聚合包与已退役包）。 */
function childPlugins() {
  return readdirSync(join(ROOT, 'packages'))
    .filter((d) => d.startsWith('dsh-') && d !== AGGREGATE_NAME && !RETIRED.has(d))
    .sort()
}

/** 解析子包 cordis.patch.yml 的 insert 行 -> [{ id, name }]（丢弃 config/注释）。 */
function parsePatchRows(child) {
  const text = readFileSync(join(ROOT, 'packages', child, 'cordis.patch.yml'), 'utf8')
  const rows = []
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*-\s+id:\s*(\S+)/)
    if (m) {
      const nameM = /^\s*name:\s*['"]?([^'"]+)['"]?\s*$/.exec(
        text.split('\n')[text.split('\n').indexOf(line) + 1] ?? '',
      )
      rows.push({ id: m[1], name: nameM ? nameM[1] : '' })
    }
  }
  return rows
}

/** 生成聚合 cordis.patch.yml 内容（子包行原样拼接，不带 config）。 */
function renderPatch(children) {
  const lines = [
    '# AUTO-GENERATED by scripts/aggregate.ts — do not edit',
    '# 聚合行 = 各独立包 cordis.patch.yml 的 insert 行原样拼接（id + name，无 config，',
    '# 配置走 schema 默认值）。改独立包 patch 后运行 `node scripts/aggregate.ts` 重新生成。',
    '- insert:',
  ]
  for (const child of children) {
    const rows = parsePatchRows(child)
    if (rows.length === 0) {
      console.error(`[aggregate] ${child}: 未解析到 insert 行`)
      process.exit(1)
    }
    for (const { id, name } of rows) {
      lines.push(`    - id: ${id}`)
      lines.push(`      name: '${name}'`)
    }
  }
  return lines.join('\n') + '\n'
}

const children = childPlugins()
const generated = renderPatch(children)

if (CHECK) {
  const onDisk = existsSync(PATCH_PATH) ? readFileSync(PATCH_PATH, 'utf8') : ''
  if (onDisk !== generated) {
    console.error(`[aggregate] check FAILED: ${AGGREGATE_NAME}/cordis.patch.yml 与生成内容漂移——运行 node scripts/aggregate.ts`)
    process.exit(1)
  }
  console.log(`[aggregate] check OK: ${AGGREGATE_NAME}（${children.length} 个子包，行数一致）`)
  process.exit(0)
}

writeFileSync(PATCH_PATH, generated)
console.log(`[aggregate] 已生成 ${AGGREGATE_NAME}/cordis.patch.yml（${children.length} 个子包行原样拼接，无 config）`)