/**
 * dsh-jev-decide 双端共享面门面（跨模块引用唯一入口；本文件只转出、不放实现）。
 *
 * 同级模块构建硬约束：本目录仅 contract.ts 一个纯模块（零 import）。
 */
export {
  API_KEY_REF_RE,
  CJK_RE,
  CONFIG_FILE_NAME,
  CONFIG_VERSION,
  CUSTOM_PRESETS_VERSION,
  JEV_BASE_URL,
  JEV_MODEL,
  MAX_CUSTOM_DESCRIPTION,
  MAX_CUSTOM_LABEL,
  MAX_CUSTOM_PRESETS,
  MAX_QUESTIONS,
  MAX_QUESTION_TEXT,
  PACKAGE_DIR,
  PRESETS_FILE_NAME,
  PRESET_ID_RE,
  QUESTION_ID_RE,
  RETIRED_KEYS,
  ROUTES,
  SECRETS_FILE_NAME,
  SESSION_ID_RE,
  SNIPPET_MAX,
  TEMPLATE_VERSION,
  CUSTOM_PRESETS_FILE_NAME,
  VERSION_FILE_NAME,
  FROZEN_PRESETS,
  containsCjk,
  frozenPresetOf,
  keyShapeCategory,
  truncateCodePoints,
} from "./contract.ts";
export type {
  AutomationCap,
  AutomationLevel,
  ConfigV1,
  CustomPreset,
  DecideOutput,
  ErrorEnvelope,
  HistoryEntry,
  HistoryQuestion,
  JevLang,
  JevTier,
  KeyShapeCategory,
  PresetTemplate,
} from "./contract.ts";
